name: ci

on:
  push:
    branches:
      - master

env:
  GO111MODULE: on

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go build -modfile=go.local.mod
        working-directory: example
      - run: go build
        working-directory: example
